### ISSUE TITLE
[Feature] Unicode Character Support (SQL Database)

### ISSUE THREAD

**Issue by EnderGamingFilms** [chris3105x/EasyPrefix#8]
**Plugin Version:** 1.6.5
**Minecraft Version:**  (Paper Spigot) 1.15.2-R0.1-SNAPSHOT

**Summary:**
Could you make it so Unicode characters can be stored in the SQL Database? For example characters like <code>►</code> and <code>»</code>

**Comment by chris3105x** [comment]
Fixed.
Thank you so much!!!

**Comment by EnderGamingFilms** [comment]
Still not fixed. Suffix is still varchar 128. I believe it needs to be something like "utf8mb4" or "utf8mb4_unicode_ci".
![image](https://user-images.githubusercontent.com/25815579/85994645-f2f6de80-b9ac-11ea-9676-921360d94f9c.png)
